package com.vito.web.entity;

import java.util.Date;

public class TImpawnInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_impawn_info.Borrow_id
     *
     * @mbg.generated
     */
    private String borrowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_impawn_info.Cust_id
     *
     * @mbg.generated
     */
    private String custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_impawn_info.Agency_id
     *
     * @mbg.generated
     */
    private String agencyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_impawn_info.Pawn_goods_name
     *
     * @mbg.generated
     */
    private String pawnGoodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_impawn_info.Pawn_goods_num
     *
     * @mbg.generated
     */
    private Integer pawnGoodsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_impawn_info.Contract_date
     *
     * @mbg.generated
     */
    private Date contractDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_impawn_info.Borrow_id
     *
     * @return the value of t_impawn_info.Borrow_id
     *
     * @mbg.generated
     */
    public String getBorrowId() {
        return borrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_impawn_info.Borrow_id
     *
     * @param borrowId the value for t_impawn_info.Borrow_id
     *
     * @mbg.generated
     */
    public void setBorrowId(String borrowId) {
        this.borrowId = borrowId == null ? null : borrowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_impawn_info.Cust_id
     *
     * @return the value of t_impawn_info.Cust_id
     *
     * @mbg.generated
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_impawn_info.Cust_id
     *
     * @param custId the value for t_impawn_info.Cust_id
     *
     * @mbg.generated
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_impawn_info.Agency_id
     *
     * @return the value of t_impawn_info.Agency_id
     *
     * @mbg.generated
     */
    public String getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_impawn_info.Agency_id
     *
     * @param agencyId the value for t_impawn_info.Agency_id
     *
     * @mbg.generated
     */
    public void setAgencyId(String agencyId) {
        this.agencyId = agencyId == null ? null : agencyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_impawn_info.Pawn_goods_name
     *
     * @return the value of t_impawn_info.Pawn_goods_name
     *
     * @mbg.generated
     */
    public String getPawnGoodsName() {
        return pawnGoodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_impawn_info.Pawn_goods_name
     *
     * @param pawnGoodsName the value for t_impawn_info.Pawn_goods_name
     *
     * @mbg.generated
     */
    public void setPawnGoodsName(String pawnGoodsName) {
        this.pawnGoodsName = pawnGoodsName == null ? null : pawnGoodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_impawn_info.Pawn_goods_num
     *
     * @return the value of t_impawn_info.Pawn_goods_num
     *
     * @mbg.generated
     */
    public Integer getPawnGoodsNum() {
        return pawnGoodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_impawn_info.Pawn_goods_num
     *
     * @param pawnGoodsNum the value for t_impawn_info.Pawn_goods_num
     *
     * @mbg.generated
     */
    public void setPawnGoodsNum(Integer pawnGoodsNum) {
        this.pawnGoodsNum = pawnGoodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_impawn_info.Contract_date
     *
     * @return the value of t_impawn_info.Contract_date
     *
     * @mbg.generated
     */
    public Date getContractDate() {
        return contractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_impawn_info.Contract_date
     *
     * @param contractDate the value for t_impawn_info.Contract_date
     *
     * @mbg.generated
     */
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }
}