package com.vito.web.mapper;

import com.vito.web.entity.TImpawnInfo;
import java.util.List;

public interface TImpawnInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_impawn_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String borrowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_impawn_info
     *
     * @mbg.generated
     */
    int insert(TImpawnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_impawn_info
     *
     * @mbg.generated
     */
    TImpawnInfo selectByPrimaryKey(String borrowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_impawn_info
     *
     * @mbg.generated
     */
    List<TImpawnInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_impawn_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TImpawnInfo record);
}